% Want to distribute this code? Have other questions? -> sbowman@stanford.edu
function TrainModel(dataflag, pretrainingFilename, expName, mbs, dim, lr, lambda, tot, sig)

echo "cd quant; mbs = [16]; name=['test-sick-only-',num2str(mbs)]; disp(name); TrainModel('sick-only', '', name, mbs, 25, 0.01, 0.001, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = [16]; name=['sick-only-',num2str(mbs)]; disp(name); TrainModel('sick-only', '', name, mbs, 25, 0.01, 0.001, 1, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = [16]; name=['sick-only-2']; disp(name); TrainModel('sick-only', '', name, mbs, 25, 0.01, 0.001, 1, 0);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = [16]; name=['sick-plus-',num2str(mbs)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, 0.01, 0.001, 1, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = [16]; name=['sick-plus-full-',num2str(mbs)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, 0.01, 0.001, 1, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = [16]; name=['sick-plus-clean-',num2str(mbs)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, 0.01, 0.01, 1, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.01; lr = 0.1; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('sick-plus', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.001; lr = 0.1; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('sick-plus', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00001; lr = 0.1; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('sick-plus', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; lr = 0.01; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('sick-plus', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00001; lr = 0.01; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('sick-plus', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.001; lr = 0.001; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('sick-plus', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.001; lr = 0.001; name=['word-relations-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.001; lr = 0.0001; name=['word-relations-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; lr = 0.01; name=['word-relations-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; lr = 0.001; name=['word-relations-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00001; lr = 0.01; name=['word-relations-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0001; lr = 0.01; name=['wr-frozen-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; lr = 0.1; name=['wr-frozen-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00003; lr = 0.1; name=['wr-frozen-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.00003; lr = 0.1; name=['gradcheck1-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('gradcheck', '', name, 48, 25, 2, lr, lambda, 1, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.003; lr = 0.1; name=['gradcheck2-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('gradcheck', '', name, 48, 25, 2, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00003; lr = 0.1; name=['gradcheck3-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('gradcheck', '', name, 48, 25, 2, lr, lambda, 1, 2);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0001; lr = 0.01; name=['wr-frozen-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; lr = 0.1; name=['wr-frozen-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00003; lr = 0.1; name=['wr-frozen-', num2str(lr), '-', num2str(lambda)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, 1);" | /afs/cs/software/bin/matlab_r2012b


echo "cd quant; lambda = 0.0001; lr = 0.03; ed = 0; name=['wr-tfrozen-', num2str(lr), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; lr = 0.1; ed = 0; name=['wr-tfrozen-', num2str(lr), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; lr = 0.03; ed = 1; name=['wr-tfrozen-', num2str(lr), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; lr = 0.1; ed = 1; name=['wr-tfrozen-', num2str(lr), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; lr = 0.03; ed = 2; name=['wr-tfrozen-', num2str(lr), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; lr = 0.1; ed = 2; name=['wr-tfrozen-', num2str(lr), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, 48, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.000001; lr = 0.01; mbs = 16; trainwords = true; ed = 0; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000001; lr = 0.1; mbs = 16; trainwords = true; ed = 0; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000001; lr = 0.01; mbs = 16; trainwords = true; ed = 1; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000001; lr = 0.1; mbs = 16; trainwords = true; ed = 1; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000001; lr = 0.01; mbs = 16; trainwords = true; ed = 2; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000001; lr = 0.1; mbs = 16; trainwords = true; ed = 2; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0005; lr = 0.1; ed = 0; mbs = 16; name=['wr-tfrozen-', num2str(mbs), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, mbs, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; lr = 0.1; ed = 1; mbs = 16; name=['wr-tfrozen-', num2str(mbs), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, mbs, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.005; lr = 0.1; ed = 0; mbs = 16; name=['wr-tfrozen-', num2str(mbs), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, mbs, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.005; lr = 0.1; ed = 1; mbs = 16; name=['wr-tfrozen-', num2str(mbs), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, mbs, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; lr = 0.1; ed = 1; mbs = 64; name=['wr-tfrozen-', num2str(mbs), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, mbs, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.005; lr = 0.1; ed = 0; mbs = 64; name=['wr-tfrozen-', num2str(mbs), '-', num2str(lambda), '-', num2str(ed)]; disp(name); TrainModel('word-relations', '', name, mbs, 25, lr, lambda, 1, ed);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.000001; lr = 0.1; mbs = 16; trainwords = true; ed = 0; name=['sick-plus-demo-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, 80, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b

# TODO: Turn on word loading
# TODO: try not training words?
function TrainModel(dataflag, pretrainingFilename, expName, mbs, dim, penult, lr, lambda, tot, transDepth, trainwords)

echo "cd quant; lambda = 0.0005; ed = 0; train = 0; penult = 80, name=['wr-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.001; ed = 0; train = 0; penult = 15, name=['wr-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 0; penult = 80, name=['wr-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.001; ed = 1; train = 0; penult = 15, name=['wr-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 2; train = 0; penult = 80, name=['wr-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0005; ed = 2; train = 0; penult = 15, name=['wrtest-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.000001; lr = 0.01; mbs = 16; trainwords = true; ed = 0; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000001; lr = 0.1; mbs = 16; trainwords = true; ed = 0; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000001; lr = 0.01; mbs = 16; trainwords = true; ed = 1; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000001; lr = 0.1; mbs = 16; trainwords = true; ed = 1; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000001; lr = 0.01; mbs = 16; trainwords = true; ed = 2; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000001; lr = 0.1; mbs = 16; trainwords = true; ed = 2; name=['sick-plus-clean-', num2str(lr), '-', num2str(lambda), '-', num2str(mbs), '-', num2str(ed), '-', num2str(trainwords)]; disp(name); TrainModel('sick-plus', '', name, mbs, 25, lr, lambda, 1, ed, trainwords);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0005; ed = 0; train = 0; penult = 15, name=['sick-plus-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 0; train = 1; penult = 15, name=['sick-plus-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 0; penult = 15, name=['sick-plus-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 0; penult = 15, name=['sick-plus-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 2; train = 1; penult = 15, name=['sick-plus-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 2; train = 0; penult = 15, name=['sick-plus-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b


echo "cd quant; lambda = 0.0005; ed = 0; train = 0; penult = 80, name=['wr-f-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.001; ed = 0; train = 0; penult = 15, name=['wr-f-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 0; penult = 80, name=['wr-f-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.001; ed = 1; train = 0; penult = 15, name=['wr-f-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 2; train = 0; penult = 80, name=['wr-f-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.001; ed = 2; train = 0; penult = 80, name=['wr-f-tfrozen-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('word-relations', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0005; ed = 0; train = 0; penult = 15, name=['sick-plus-f-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 0; train = 1; penult = 15, name=['sick-plus-f-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 0; penult = 15, name=['sick-plus-f-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 0; penult = 15, name=['sick-plus-f-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 2; train = 1; penult = 15, name=['sick-plus-f-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 2; train = 0; penult = 15, name=['sick-plus-f-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('sick-plus', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b


echo "cd quant; mbs = 16; lambda = 0.0005; ed = 0; train = 0; penult = 80, name=['ss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 16; lambda = 0.0005; ed = 1; train = 0; penult = 80, name=['ss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.001; ed = 1; train = 0; penult = 15, name=['ss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.001; ed = 2; train = 0; penult = 80, name=['ss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 16; lambda = 0.0005; ed = 2; train = 1; penult = 80, name=['ss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.001; ed = 0; train = 1; penult = 15, name=['ss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 16; lambda = 0.0005; ed = 1; train = 1; penult = 15, name=['ss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; train = 0; penult = 80, name=['ss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.001; ed = 2; train = 0; penult = 15, name=['ss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, train);" | /afs/cs/software/bin/matlab_r2012b


echo "cd quant; mbs = 64; lambda = 0.0005; ed = 0; loadWords = 0; penult = 45, dp = 1, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 1, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.001; ed = 0; loadWords = 0; penult = 80, dp = 1, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.001; ed = 1; loadWords = 0; penult = 45, dp = 1, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0001; ed = 1; loadWords = 1; penult = 80, dp = 1, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 16; lambda = 0.001; ed = 0; loadWords = 0; penult = 45, dp = 1, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b


echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 0.75, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 0.5, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 0.75, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 0.5, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b

#

echo "cd quant; mbs = 8; lambda = 0.0005; ed = 1; loadWords = 1; penult = 150, dp = 0.33, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 8; lambda = 0.0005; ed = 1; loadWords = 1; penult = 100, dp = 0.33, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 0.33, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 0.16, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 0.33, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 0.16, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 0.33, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 0.16, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 0.33, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 0.16, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b


restart quant/orss-l0.0005-ed1-tr0-pen80-mbs64-dp0.33/stat_log

echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 0.75, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 0.33, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 1, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 1, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 0.75, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 0.16, name=['orss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 0.75, name=['oss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 0.75, name=['orbss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 0.33, name=['orbss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 0.16, name=['orbss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs,25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b


# Crossfolding 

echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 1, name=['orbss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = .33, name=['orbss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = .11, name=['orbss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 1, name=['orbss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = .33, name=['orbss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = .11, name=['orbss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 0, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 1, name=['otss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = .33, name=['otss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = .11, name=['otss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 1, name=['otss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = .33, name=['otss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = .11, name=['otss-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); Crossvalidate('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 1, ed, loadWords, dp);" | /afs/cs/software/bin/matlab_r2012b

# Join

echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['join1-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, mbs, 11, 1, lambda, 90, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['join2-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, mbs, 11, 1, lambda, 90, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['join3-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, mbs, 11, 1, lambda, 90, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['join4-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, mbs, 11, 1, lambda, 90, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['join5-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, mbs, 11, 1, lambda, 90, 0);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['join1R-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, mbs, 11, 0, lambda, 75, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['join2R-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, mbs, 11, 0, lambda, 75, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['join3R-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, mbs, 11, 0, lambda, 75, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['join4R-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, mbs, 11, 0, lambda, 75, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['join5R-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, mbs, 11, 0, lambda, 75, 0);" | /afs/cs/software/bin/matlab_r2012b


echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['joinf1-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, 'fold1', mbs, 11, 1, lambda, 90, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['joinf2-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, 'fold2', mbs, 11, 1, lambda, 90, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['joinf3-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, 'fold3', mbs, 11, 1, lambda, 90, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['joinf4-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, 'fold4', mbs, 11, 1, lambda, 90, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['joinf5-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, 'fold5', mbs, 11, 1, lambda, 90, 0);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['joinf1R-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, 'fold1', mbs, 11, 0, lambda, 75, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['joinf2R-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, 'fold2', mbs, 11, 0, lambda, 75, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['joinf3R-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, 'fold3', mbs, 11, 0, lambda, 75, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['joinf4R-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, 'fold4', mbs, 11, 0, lambda, 75, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant/join-table; mbs = 64; lambda = 0.0005; ed = 1; penult = 80, name=['joinf5R-l', num2str(lambda), '-ed', num2str(ed), '-pen', num2str(penult), '-mbs', num2str(mbs)]; disp(name);  TrainJoinModel(name, 'fold5', mbs, 11, 0, lambda, 75, 0);" | /afs/cs/software/bin/matlab_r2012b


echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 1; penult = 80, dp = 1, name=['otss-2-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 1, ed, loadWords, dp, 5);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 1, name=['otss-2-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 1, ed, loadWords, dp, 3);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 1, name=['otss-2-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 1, ed, loadWords, dp, 4);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; mbs = 64; lambda = 0.0005; ed = 1; loadWords = 0; penult = 80, dp = 1, name=['otss-2-l', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(loadWords), '-pen', num2str(penult), '-mbs', num2str(mbs), '-dp', num2str(dp)]; disp(name); TrainModel('synset-relations', '', name, mbs, 25, penult, 0.1, lambda, 1, ed, loadWords, dp, 5);" | /afs/cs/software/bin/matlab_r2012b

# Back to SICK

function 																																											TrainModel(dataflag, pretrainingFilename, expName, mbs, dim, penult, lr, lambda, tot, transDepth, loadwords, dsp, fold)

echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75, name=['if-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('imageflickr', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 1; train = 0; penult = 75, name=['if-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('imageflickr', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 0; train = 1; penult = 75, name=['if-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('imageflickr', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 0; train = 0; penult = 75, name=['if-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('imageflickr', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 0; train = 0; penult = 75, name=['if-r-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('imageflickr', '', name, 64, 25, penult, 0.1, lambda, 0, ed, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75, name=['if-reproc-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult)]; disp(name); TrainModel('imageflickr', '', name, 64, 25, penult, 0.1, lambda, 1, ed, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b

																																					dataflag, transDepth, penult, lambda, tot, mbs, lr, trainwords
echo "cd quant; lambda = 0.0005; ed = 0; train = 0; penult = 75; lr = 0.1, name=['if-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 0; train = 0; penult = 75; lr = 0.01, name=['if-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.005; ed = 0; train = 0; penult = 75; lr = 0.001, name=['if-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 0; train = 1; penult = 75; lr = 0.1, name=['if-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.005; ed = 0; train = 1; penult = 75; lr = 0.01, name=['if-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 0; train = 1; penult = 75; lr = 0.001, name=['if-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['if-frag-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 64, lr, train, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['if-nofrag-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 64, lr, train, 0);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['ift-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train, 0, 0);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant;TrainModel('', 'test', 1, @GradCheck, 1, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant;TrainModel('', 'test', 1, @GradCheck, 1, 1, 0);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['ift-frag-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 64, lr, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['ift-nofrag-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 64, lr, train, 0, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['ift-frag-full-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train, 0, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.05; ed = 1; train = 1; penult = 75; lr = 1, name=['ifm-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 0; penult = 75; lr = 0.01, name=['ifm-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000005; ed = 1; train = 1; penult = 75; lr = 0.001, name=['ifm-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.05; ed = 1; train = 0; penult = 75; lr = 0.001, name=['ifm-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 1, name=['ifm-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['ifm-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickr', ed, penult, lambda, 1, 64, lr, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['ifm-frag-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 64, lr, train, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['ifm-nofrag-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 64, lr, train, 0, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['ifm-nofrag-fet-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 64, lr, train, 0, 0, 0);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant;TrainModel('', 'test', 1, @GradCheck, 1, 1, 1, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant;TrainModel('', 'test', 1, @GradCheck, 1, 1, 1, 1, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant;TrainModel('', 'test', 1, @GradCheck, 1, 1, 1, 0, 0);" | /afs/cs/software/bin/matlab_r2012b
GradCheck(transDepth, topDepth, tot, trainwords, fastemb)


										SynsetRelations(transDepth, penult, lambda, tot, mbs, lr, trainwords)
echo "cd quant; name=['syns-test']; disp(name); TrainModel('', name, 1, @SynsetRelations, 1, 25, 0.0005, 1, 64, 0.1, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; name=['syns-test-1l']; disp(name); TrainModel('', name, 1, @SynsetRelations, 1, 25, 0.005, 1, 64, 0.1, 1, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; name=['syns-test-1']; disp(name); TrainModel('', name, 1, @SynsetRelations, 1, 25, 0.0005, 1, 64, 0.1, 1, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; name=['syns-test-0']; disp(name); TrainModel('', name, 1, @SynsetRelations, 1, 25, 0.0005, 1, 64, 0.1, 1, 0);" | /afs/cs/software/bin/matlab_r2012b

																																																									dataflag, transDepth, penult, lambda, tot, mbs, lr, trainwords, frag, loadwords, fastEmb
echo "cd quant; lambda = 0.005; ed = 1; train = 1; mbs = 16; penult = 75; lr = 0.1; dataflag='sick-plus-10k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 1, 0.01);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; mbs = 4; penult = 75; lr = 0.01; dataflag='sick-plus-10k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 1, 0.1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 0; mbs = 64; penult = 75; lr = 0.1; dataflag='sick-plus-10k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 0, 0.001);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 1; train = 1; mbs = 16; penult = 75; lr = 0.01; dataflag='sick-plus-100k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 1, 0.01);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 0; train = 1; mbs = 64; penult = 75; lr = 0.01; dataflag='sick-plus-100k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 1, 0.001);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; mbs = 4; penult = 75; lr = 0.001; dataflag='sick-plus-100k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 1, 0.1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.005; ed = 1; train = 1; mbs = 256; penult = 75; lr = 0.1; dataflag='sick-plus-100k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 1, 0.01);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.000005; ed = 0; train = 1; mbs = 16; penult = 75; lr = 0.001; dataflag='sick-plus-100k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 1, 0.01);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 0; mbs = 4; penult = 75; lr = 0.1; dataflag='sick-plus-100k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 0, 0.001);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.005; ed = 1; train = 0; mbs = 16; penult = 75; lr = 0.001; dataflag='sick-plus-100k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 0, 0.01);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.00005; ed = 1; train = 1; mbs = 4; penult = 75; lr = 0.01; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 1, 0.01);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 1; train = 0; mbs = 16; penult = 75; lr = 0.1; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-mbs', num2str(mbs), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, mbs, lr, train, 0, 1, 1, 0.1);" | /afs/cs/software/bin/matlab_r2012b

# Post

transDepth, topDepth, tot, summing, trainwords, fastemb
echo "cd quant;TrainModel('', 'test', 1, @GradCheck, 0, 1, 1, 0, 1, 0);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.001; ed = 0; train = 1; penult = 75; lr = 0.01; loadw = 0; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 64, lr, train, 0, loadw, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.001; ed = 0; train = 1; penult = 75; lr = 0.01; loadw = 0; dataflag='sick-only'; name=[dataflag, 'slow', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 64, lr, train, 0, loadw, 0);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.005; ed = 0; train = 1; penult = 75; lr = 0.01; loadw = 0; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 64, lr, train, 0, loadw, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.001; ed = 0; train = 1; penult = 75; lr = 0.01; loadw = 0; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 64, lr, train, 0, loadw, 0);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.005; ed = 0; train = 1; penult = 75; lr = 0.01; loadw = 1; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 64, lr, train, 0, loadw, 1);" | /afs/cs/software/bin/matlab_r2012b

# @ Sep 26

echo "cd quant; lambda = 0.001; ed = 0; train = 1; penult = 75; lr = 0.01; loadw = 0; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 16, lr, train, 0, loadw, 0, 0.01);" | /afs/cs/software/bin/matlab_r2012b

 
echo "cd quant-old; for mbs = [16] name=['quant-old-1',num2str(mbs)]; TrainModel('sick-only', '', name, mbs, 25, 0.01, 0.001, 1, 0); end;" | /afs/cs/software/bin/matlab_r2012b
function TrainJoinModel 													(dataflag, pretrainingFilename, expName, mbs, dim, lr, lambda, tot, frag)
sick-only

function [ hyperParams, options, wordMap, relationMap ] = Sick(dataflag, transDepth, penult, lambda, tot, mbs, lr, trainwords, frag, loadwords, fastEmb, scale)

echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.01, name=['ifp-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 16, lr, train, 0, 1, 0, 0.01);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['ifp-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 64, lr, train, 0, 1, 1, 0.01);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 0; penult = 75; lr = 0.1, name=['ifp-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 32, lr, train, 0, 1, train, 0.05);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.01, name=['ifp-fe-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, 0, 1, 1, 0.01);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.01, name=['ifp-5x-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, 0, 1, 0, 0.05);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.1, name=['ifp-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, 0, 1, 0, 0.01);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0005; ed = 0; train = 0; penult = 75; lr = 0.1, name=['if-sum-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 0, 1, 16, lr, train, 0, 1, 0, 0.01);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 0; train = 0; penult = 75; lr = 0.1, name=['sick-only-sum-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'sick-only', ed, penult, lambda, 0, 1, 16, lr, train, 0, 1, 0, 0.01);" | /afs/cs/software/bin/matlab_r2012b


echo "cd quant; lambda = 0.005; ed = 0; train = 0; penult = 75; lr = 0.1, name=['if-sum-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 0, 1, 16, lr, train, 1, 0.01, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.005; ed = 0; train = 0; penult = 75; lr = 0.1, name=['sick-only-sum-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'sick-only', ed, penult, lambda, 0, 1, 16, lr, train, 1, 0.01, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 0; train = 0; penult = 75; lr = 0.1, name=['if-sum-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 0, 1, 16, lr, train, 1, 0.01, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 0; train = 0; penult = 75; lr = 0.1, name=['sick-only-sum-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'sick-only', ed, penult, lambda, 0, 1, 16, lr, train, 1, 0.01, 1);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.01, name=['ifp2-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, 1, 0.05, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.001, name=['ifp2-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, 1, 0.05, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.01, name=['ifp2-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, 1, 0.05, 1);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 0; train = 1; penult = 75; lr = 0.01, name=['ifp2-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, 1, 0.05, 1);" | /afs/cs/software/bin/matlab_r2012b

																																																										Sick(dataflag, transDepth, penult, lambda, tot, summing, mbs, lr, trainwords, loadwords, scale, dropout)
echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 1; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 0.75; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 0.75; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant;TrainModel('', 'test', 1, @GradCheck, 0, 1, 0, 0, 1, 0);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 0.85; name=['ifp2-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2013b
echo "cd quant; lambda = 0.000005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 0.85; name=['ifp2-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2013b
echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 1; name=['ifp2-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2013b
echo "cd quant; lambda = 0.00005; ed = 2; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 1; name=['ifp2-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2013b
echo "cd quant; lambda = 0.00005; ed = 2; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 1; name=['ifp2r-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 0, 0, 16, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2013b

echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 0.85; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 0.87; dataflag='sick-only'; name=[dataflag, 'r',  num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 0, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.5; dropout = 0.85; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.00005; ed = 2; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.05; dropout = 0.85; dataflag='sick-only-b'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.1; dropout = 0.85; name=['ifp3-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort', ed, penult, lambda, 1, 0, 16, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2013b
echo "cd quant; lambda = 0.00005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.1; dropout = 0.85; name=['ifp3-100-', num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, 'imageflickrshort100', ed, penult, lambda, 1, 0, 16, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2013b

echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 1; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.1; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.01; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 0; penult = 75; lr = 0.01; loadw = 1; scale = 1; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0005; ed = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.001; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0003; ed = 1; td = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.1; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0003; ed = 1; td = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.03; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0003; ed = 1; td = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.3; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; ed = 1; td = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.1; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.001; ed = 1; td = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.1; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0003; ed = 1; td = 1; train = 0; penult = 75; lr = 0.01; loadw = 1; scale = 0.1; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0003; ed = 1; td = 1; train = 1; penult = 45; lr = 0.01; loadw = 1; scale = 0.1; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0003; ed = 1; td = 1; train = 1; penult = 90; lr = 0.01; loadw = 1; scale = 0.1; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0003; ed = 2; td = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.3; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0003; ed = 2; td = 2; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.3; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0003; ed = 1; td = 2; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.3; dropout = 0.87; dataflag='sick-only'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b


echo "cd quant; lambda = 0.0003; ed = 1; td = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.3; dropout = 0.87; dataflag='sick-plus-10k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0001; ed = 1; td = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.3; dropout = 0.87; dataflag='sick-plus-10k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
echo "cd quant; lambda = 0.0003; ed = 1; td = 1; train = 1; penult = 75; lr = 0.003; loadw = 1; scale = 0.3; dropout = 0.87; dataflag='sick-plus-10k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b

echo "cd quant; lambda = 0.0003; ed = 1; td = 1; train = 1; penult = 75; lr = 0.01; loadw = 1; scale = 0.3; dropout = 0.87; dataflag='sick-plus-100k'; name=[dataflag, num2str(lambda), '-ed', num2str(ed), '-td', num2str(td), '-tr', num2str(train), '-pen', num2str(penult), '-lr', num2str(lr), '-loadw', num2str(loadw), '-scale', num2str(scale), '-do', num2str(dropout)]; disp(name); TrainModel('', name, 1, @Sick, dataflag, ed, td, penult, lambda, 1, 0, 32, lr, train, loadw, scale, dropout);" | /afs/cs/software/bin/matlab_r2012b
