% Want to distribute this code? Have other questions? -> sbowman@stanford.edu
function freshModelState = TransferInitialization(freshModelState, pretrainedModelState)
% Set up for transfer learning: copy sentence embedding parameters but not
% classifier parameters into a new model state.

% Unpack fresh model state.
[ mergeMatrices, mergeMatrix, ...
    softmaxMatrix, ~, ~, ...
    ~, ~, classifierExtraMatrix, ~] ...
    = stack2param(freshModelState.theta, freshModelState.thetaDecoder);

% Unpack pretrained model state.
[ ~, ~, ...
    ~, wordFeatures, connectionMatrix, ...
    compositionMatrix, scoringVector, ~, embeddingTransformMatrix] ...
    = stack2param(pretrainedModelState.theta, pretrainedModelState.thetaDecoder);

% Pack up the combination.
[ freshModelState.theta, freshModelState.thetaDecoder ] = param2stack(mergeMatrices, mergeMatrix, ...
    softmaxMatrix, wordFeatures, connectionMatrix, ...
    compositionMatrix, scoringVector, classifierExtraMatrix, embeddingTransformMatrix);

freshModelState.separateWordFeatures = pretrainedModelState.separateWordFeatures;

end
