% SICK experiments

export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-c'; name='adn'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 1e-7);" ; qsub -v MATLABCMD quant/run.sh -q john
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-c'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 1e-7);" ; qsub -v MATLABCMD quant/run.sh -q john

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.11);" ; qsub -v MATLABCMD quant/run.sh -q john


export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.11);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-2-100k'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-2-100k'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.11);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.11);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 1.00);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.95; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.85; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.15; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.05; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 0; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 1; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 3; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 3; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12


export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 1; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.00001; dim = 25; ed = 200; td = 3; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 4; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 25; ed = 300; td = 2; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 12; collo = 3; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 300; td = 1; penult = 75; lr = 0; dropout = [0.5\, 0.5]; tot = 2; mult = 8; collo = 3; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 100; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.5\, 0.5]; tot = 2; mult = 12; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 200; td = 2; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.00001; dim = 35; ed = 200; td = 2; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 35; ed = 300; td = 3; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 3; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 35; ed = 200; td = 2; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 300; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 3; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 75; ed = 200; td = 2; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 75; ed = 200; td = 3; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 0; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 1; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 3; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 3; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

john6.stanford.edu - 871234.scail.stanford.edu - cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75, 0.9]; tot = 2; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel('', 1, @Sick, name, dataflag, ed, dim, td, penult, lambda, tot, 0, mbs, lr, dropout(1), dropout(2), mult, collo, 1, 1);

r


export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-c'; name='adn'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-c'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, collo\, tscale\, wscale\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john


export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 3; penult = 75; lr = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b-sgm'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12



export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-only'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='ssick-only'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-only'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-only'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-only'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-only'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 3; penult = 75; lr = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; collo = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-only'; name='sick-test-b-sgm'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12


# Wait on first and last, run on john