# Recursion experiments

echo "dataflag = 'and-or-deep'; lambda = 0.001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 1; name='demo'; relu = 1; TrainModel('', 1, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 1; name='demo'; relu = 1; TrainModel('', 2, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 1; name='demo'; relu = 1; TrainModel('', 3, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 1; name='demo'; relu = 1; TrainModel('', 4, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 1; name='demo'; relu = 1; TrainModel('', 5, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay

echo "dataflag = 'and-or-deep'; lambda = 0.0003; dim = 45; td = 1; penult = 75; dropout = 1; tot = 0; name='demo'; relu = 1; TrainModel('', 1, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.0003; dim = 45; td = 1; penult = 75; dropout = 1; tot = 0; name='demo'; relu = 1; TrainModel('', 2, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.0003; dim = 45; td = 1; penult = 75; dropout = 1; tot = 0; name='demo'; relu = 1; TrainModel('', 3, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.0003; dim = 45; td = 1; penult = 75; dropout = 1; tot = 0; name='demo'; relu = 1; TrainModel('', 4, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.0003; dim = 45; td = 1; penult = 75; dropout = 1; tot = 0; name='demo'; relu = 1; TrainModel('', 5, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay

echo "dataflag = 'and-or-deep'; lambda = 0.0003; dim = 45; td = 1; penult = 75; dropout = 1; tot = -1; name='demo'; relu = 1; TrainModel('', 1, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.0003; dim = 45; td = 1; penult = 75; dropout = 1; tot = -1; name='demo'; relu = 1; TrainModel('', 2, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.0003; dim = 45; td = 1; penult = 75; dropout = 1; tot = -1; name='demo'; relu = 1; TrainModel('', 3, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.0003; dim = 45; td = 1; penult = 75; dropout = 1; tot = -1; name='demo'; relu = 1; TrainModel('', 4, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "dataflag = 'and-or-deep'; lambda = 0.0003; dim = 45; td = 1; penult = 75; dropout = 1; tot = -1; name='demo'; relu = 1; TrainModel('', 5, @AndOr, name, dataflag, dim, penult, td, lambda, tot, relu, dropout, 32);" | /afs/cs/software/bin/matlab_r2012b -nodisplay
