% Quantification and negation experiments

echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 0; name='demo'; relu = 1; TrainModel('', 1, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 0; name='demo'; relu = 1; TrainModel('', 2, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 0; name='demo'; relu = 1; TrainModel('', 3, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 0; name='demo'; relu = 1; TrainModel('', 4, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 0; name='demo'; relu = 1; TrainModel('', 5, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay

echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 1; name='demo'; relu = 1; TrainModel('', 1, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 1; name='demo'; relu = 1; TrainModel('', 2, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 1; name='demo'; relu = 1; TrainModel('', 3, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 1; name='demo'; relu = 1; TrainModel('', 4, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = 1; name='demo'; relu = 1; TrainModel('', 5, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay

echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = -1; name='demo'; relu = 1; TrainModel('', 1, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = -1; name='demo'; relu = 1; TrainModel('', 2, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = -1; name='demo'; relu = 1; TrainModel('', 3, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = -1; name='demo'; relu = 1; TrainModel('', 4, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay
echo "cd quant; lambda = 0.0001; dim = 25; td = 1; penult = 75; dropout = 1; tot = -1; name='demo'; relu = 1; TrainModel('', 5, @Quantifiers, name, dim, penult, td, lambda, tot, relu, dropout, 32);"  | /afs/cs/software/bin/matlab_r2012b -nodisplay