export MATLABCMD="cd quant; lambda = 0.001; dim = 25; td = 2; penult = 75; comp = 1; dataflag='cv'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.01; dim = 25; td = 2; penult = 75; comp = 1; dataflag='cv'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.0001; dim = 25; td = 2; penult = 75; comp = 1; dataflag='cv'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.0001; dim = 25; td = 3; penult = 75; comp = 1; dataflag='cv'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.001; dim = 25; td = 2; penult = 75; comp = 1; dataflag='long'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  

% To run
export MATLABCMD="cd quant; lambda = 0.003; dim = 25; td = 2; penult = 75; comp = 1; dataflag='cv'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.001; dim = 25; td = 2; penult = 75; comp = 1; dataflag='cv'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.0003; dim = 25; td = 2; penult = 75; comp = 1; dataflag='cv'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.001; dim = 10; td = 2; penult = 75; comp = 1; dataflag='cv'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.001; dim = 50; td = 2; penult = 75; comp = 1; dataflag='cv'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  

export MATLABCMD="cd quant; lambda = 0.003; dim = 25; td = 2; penult = 75; comp = 1; dataflag='long'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.001; dim = 25; td = 2; penult = 75; comp = 1; dataflag='long'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.0003; dim = 25; td = 2; penult = 75; comp = 1; dataflag='long'; name='/scr/sbowman/alcir'; TrainModel(''\, 1\, @ALCIR\, name\, dataflag\, dim\, td\, penult\, lambda\, comp);" ; qsub -v MATLABCMD quant/run.sh  
