cd quant; 
lambda = 0.000001; dim = 45; ed = 50; td = 2; penult = 75; dropout = [0.5, 0.5]; tot = 2; collo = 2; dataflag='snli095-only'; name='/scr/sbowman/sst-test'; 
TrainModel('', 1, @SST, name, dataflag, ed, dim, td, penult, lambda, tot, dropout(1), dropout(2), collo, 1, 1)

export MATLABCMD="cd quant; lambda = 0.0001; dim = 200; ed = 200; td = 1; penult = 75; dropout = [1\, 1]; tot = 5; collo = 1; dataflag='sst-demo'; name='/scr/sbowman/sst-demo-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 200; ed = 200; td = 1; penult = 75; dropout = [1\, 1]; tot = 4; collo = 1; dataflag='sst-demo'; name='/scr/sbowman/sst-demo-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 200; ed = 200; td = 1; penult = 75; dropout = [1\, 1]; tot = 3; collo = 1; dataflag='sst-demo'; name='/scr/sbowman/sst-demo-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 200; ed = 200; td = 1; penult = 75; dropout = [1\, 1]; tot = 2; collo = 1; dataflag='sst-demo'; name='/scr/sbowman/sst-demo-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 200; ed = 200; td = 1; penult = 75; dropout = [1\, 1]; tot = -1; collo = 1; dataflag='sst-demo'; name='/scr/sbowman/sst-demo-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
