% SICK experiments

export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-c'; name='adn'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 1e-7);" ; qsub -v MATLABCMD quant/run.sh -q john
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-c'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 1e-7);" ; qsub -v MATLABCMD quant/run.sh -q john

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.11);" ; qsub -v MATLABCMD quant/run.sh -q john


export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.11);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-2-100k'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-2-100k'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.11);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.11);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 1.00);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.95; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.85; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.15; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.05; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='adr-2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 1; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 3; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 3; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12


export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 1; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.00001; dim = 25; ed = 200; td = 3; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 4; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 25; ed = 300; td = 2; penult = 75; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 12; wordsource = 3; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 300; td = 1; penult = 75; lr = 0; dropout = [0.5\, 0.5]; tot = 2; mult = 8; wordsource = 3; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 100; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.5\, 0.5]; tot = 2; mult = 12; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 200; td = 2; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-3r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.00001; dim = 35; ed = 200; td = 2; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 35; ed = 300; td = 3; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 3; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 35; ed = 200; td = 2; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 300; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 3; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 75; ed = 200; td = 2; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 75; ed = 200; td = 3; penult = 100; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 1; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 3; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 3; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75\, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

john6.stanford.edu - 871234.scail.stanford.edu - cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0; dropout = [0.75, 0.9]; tot = 2; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='adr-4r'; TrainModel('', 1, @Sick, name, dataflag, ed, dim, td, penult, lambda, tot, 0, mbs, lr, dropout(1), dropout(2), mult, wordsource, 1, 1);

r


export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-c'; name='adn'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-c'; name='adr'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john


export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 3; penult = 75; lr = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea'; name='sick-test-b-sgm'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12





export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 3; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 64; dataflag='sick-plus-600k-ea-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12


export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-plus-600k-ea'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; mult = 8; wordsource = 1; dataflag='sick-plus-600k-ea'; name='scr/sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12


export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 2; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='dg-only'; name='/scr/sbowman/dg-pretrain'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 200; td = 2; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 64; dataflag='dg-only'; name='/scr/sbowman/dg-pretrain'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0000001; dim = 50; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='dg-only'; name='/scr/sbowman/dg-pretrain'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 1; penult = 75; lr = 0; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='dg-only'; name='/scr/sbowman/dg-pretrain'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0000001; dim = 50; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='dg-only'; name='/scr/sbowman/dg-pretrain'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0; dim = 50; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='dg-only'; name='/scr/sbowman/dg-pretrain'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0000001; dim = 50; ed = 200; td = 3; penult = 75; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='dg-only'; name='/scr/sbowman/dg-pretrain'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0; dim = 50; ed = 200; td = 3; penult = 75; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 0.9; wscale = 0.01; mbs = 32; dataflag='dg-only'; name='/scr/sbowman/dg-pretrain'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12


export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 0);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 0.1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 0.5);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 0.7);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 0.9);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.6\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.9\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.6\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.9\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12


export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.9\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.9\, 0.9]; rtemult = 0; nlimult = 0; mult = 2; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 30; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.9\, 0.9]; rtemult = 0; nlimult = 0; mult = 3; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.9\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.9\, 0.9]; rtemult = 0; nlimult = 0; mult = 2; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 50; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.9\, 0.9]; rtemult = 0; nlimult = 0; mult = 3; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 90; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.9\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 90; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.9\, 0.9]; rtemult = 0; nlimult = 0; mult = 2; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 90; ed = 200; td = 1; penult = 75; tot = 2; dropout = [0.9\, 0.9]; rtemult = 0; nlimult = 0; mult = 3; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 90; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 0; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 90; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 90; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 2; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 90; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 0);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 90; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 90; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12



export MATLABCMD="cd quant; lambda = 0.0005; dim = 20; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 0; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 20; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 20; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 2; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0005; dim = 20; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 0);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 20; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 20; ed = 200; td = 1; penult = 75; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12


export MATLABCMD="cd quant; lambda = 0.0005; dim = 20; ed = 200; td = 3; penult = 40; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 0);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 20; ed = 200; td = 3; penult = 40; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12


export MATLABCMD="cd quant; lambda = 0.0005; dim = 20; ed = 200; td = 3; penult = 90; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 0);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0005; dim = 20; ed = 200; td = 3; penult = 90; tot = 1; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 1; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only-dev'; name='sick-test-b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, mbs\, dropout(1)\, dropout(2)\, mult\, wordsource\, 1\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12


export MATLABCMD="cd quant; decay = 0.95; mm = 0.9; lr = 0; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, decay\, mm\, lr);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; decay = 0.95; mm = 0.9; lr = 0.0001; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, decay\, mm\, lr);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; decay = 0.9; mm = 0.9; lr = 0.0001; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, decay\, mm\, lr);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; decay = 0.95; mm = 0.95; lr = 0.0001; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, decay\, mm\, lr);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; decay = 0.95; mm = 0.9; lr = 0.001; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, decay\, mm\, lr);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; decay = 0.95; mm = 0.9; lr = 0.00001; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, decay\, mm\, lr);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; decay = 0.95; mm = 0.75; lr = 0.0001; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule2'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, decay\, mm\, lr);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; conCost = 0; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule4b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, conCost);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; conCost = 3; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule4b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, conCost);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; conCost = 5; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule4b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, conCost);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; conCost = 10; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule4b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, conCost);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; conCost = 20; lambda = 0.0005; dim = 30; ed = 200; td = 2; penult = 75; comp = 5; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='sick-plus-600k-ea-dev'; name='/scr/sbowman/updaterule4b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, conCost);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; conCost = 5; lambda = 0.0005; dim = 50; ed = 200; td = 2; penult = 75; comp = 4; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='dg-only-sst'; name='/scr/sbowman/updaterule4b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, conCost);" ; qsub -v MATLABCMD quant/run.sh -q john
export MATLABCMD="cd quant; conCost = 5; lambda = 0.0005; dim = 50; ed = 200; td = 2; penult = 75; comp = 6; dropout = [0.75\, 0.75]; wordsource = 1; dataflag='dg-only-sst'; name='/scr/sbowman/updaterule4b'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, comp\, dropout(1)\, dropout(2)\, wordsource\, 1\, conCost);" ; qsub -v MATLABCMD quant/run.sh -q john


export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp2-dp1-gc0/ckpt-best-tr150522185602@435250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp2-dp1-gc0/ckpt-best-tr150522185602@435250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp7-dp1-ad1/ckpt-best-tr150521134003@97250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp7-dp1-ad1/ckpt-best-tr150521134003@97250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp2-dp1-gc0/ckpt-best-tr150522185602@435250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp2-dp1-gc0/ckpt-best-tr150522185602@435250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh


export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp
export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp7-dp1-ad1/ckpt-best-tr150521134003@97250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp
export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp
export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp7-dp1-ad1/ckpt-best-tr150521134003@97250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp


export MATLABCMD="cd quant; lambda = 0.003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp
export MATLABCMD="cd quant; lambda = 0.003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp7-dp1-ad1/ckpt-best-tr150521134003@97250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp
export MATLABCMD="cd quant; lambda = 0.003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp
export MATLABCMD="cd quant; lambda = 0.003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp7-dp1-ad1/ckpt-best-tr150521134003@97250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp

% Next round

export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp
export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp7-dp1-ad1/ckpt-best-tr150521134003@97250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp
export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp
export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp7-dp1-ad1/ckpt-best-tr150521134003@97250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp

export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp7-dp1-ad1/ckpt-best-tr150521134003@97250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 200; td = 3; penult = 100; tot = 7; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp7-dp1-ad1/ckpt-best-tr150521134003@97250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q nlp

% Next round

export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp2-dp1-gc0/ckpt-best-tr150522185602@435250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.000003; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only-transfer'; name='transfer3'; TrainModel('/scr/sbowman/snlirc2-snlirc2-only-l1e-05-dim50-ed200-td3-pen100-do1-1-co1-comp2-dp1-gc0/ckpt-best-tr150522185602@435250.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.003; dim = 50; ed = 200; td = 3; penult = 100; tot = 2; dropout = [1\, 1]; wordsource = 1; dataflag='sick-only'; name='transfer3'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

% Next round - switch to RC3 style

export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='transfer4'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150527095225@147125.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0003; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='transfer4'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150527095225@147125.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='transfer4'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150527095225@147125.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only'; name='transfer4'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0003; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only'; name='transfer4'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only'; name='transfer4'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='transfer4sm'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150527095225@147125.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0003; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='transfer4sm'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150527095225@147125.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='transfer4sm'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150527095225@147125.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='transfer4sm'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150527095225@147125.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='transfer4sm'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150527095225@147125.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.0003; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='transfer4sm'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150527095225@147125.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh

% Next round, new transfer source

export MATLABCMD="cd quant; lambda = 0.0003; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='transfer5'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150530073613@357000.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0003; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick2-only-transfer'; name='transfer5'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150530073613@357000.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='scr/sbowman/transfer5'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150530073613@357000.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick2-only-transfer'; name='transfer5'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150530073613@357000.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only'; name='transfer5'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick2-only'; name='transfer5'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only'; name='transfer5'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick2-only'; name='transfer5'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.0001; dim = 10; ed = 30; td = 1; penult = 20; tot = 2; dropout = [0.95\, 0.95]; wordsource = 0; dataflag='sick-only'; name='sick-logging-test'; TrainModel(''\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='/scr/sbowman/transfer5'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150530073613@357000.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; tot = 2; dropout = [0.95\, 0.95]; wordsource = 3; dataflag='sick-only-transfer'; name='/scr/sbowman/transfer5-tsm'; TrainModel('snlirc3d-snlirc3-only-l3e-05-dim100-ed300-td3-pen200-do0.95-0.95-co3-comp2-dp1-gc5-lstminit5/ckpt-best-tr150530073613@357000.mat'\, 1\, @Sick\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh



cd quant; 
lambda = 0.003; dim = 50; ed = 200; td = 3; penult = 100; tot = 0; dropout = [1, 1]; 
wordsource = 1; dataflag='sick-only'; name='transfer3-test'; 
TrainModel('', 1, @Sick, name, dataflag, ed, dim, td, penult, lambda, tot, dropout(1), dropout(2), wordsource, 0, -100);


