export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/subj-init'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0\, 0\, 0\, 0.1);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/subj-init'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0\, 0\, 0\, 0.1);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.000001; dim = 20; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/subj-init'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0\, 0\, 0\, 0.1);" ; qsub -v MATLABCMD quant/run.sh  

export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/subj-init'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0\, 0\, 0\, 0.1);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/subj-init'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0\, 0\, 0\, 0.1);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/subj-init'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0\, 0\, 0\, 0.1);" ; qsub -v MATLABCMD quant/run.sh  

% Best
export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/subj-init'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0\, 0\, 0\, 0.1);" ; qsub -v MATLABCMD quant/run.sh  

export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 4; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/subj-init-b'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0\, 0\, 0\, 0.1);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 4; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/subj-init-b'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0\, 0\, 0\, 0.1);" ; qsub -v MATLABCMD quant/run.sh  
export MATLABCMD="cd quant; lambda = 0.0000001; dim = 50; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 4; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/subj-init-b'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0\, 0\, 0\, 0.1);" ; qsub -v MATLABCMD quant/run.sh  

% Transfer
export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 0; dropout = [0.9\, 0.9]; tot = 2; collo = 1; dataflag='subj-transfer'; name='/scr/sbowman/subjt-'; TrainModel('snlirc-snlirc2-only-l1e-07-dim50-ed200-td3-pen100-do0.9-0.9-co1-comp2-dp1/ckpt-best-tr150517185056@353375.mat'\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo);" ; qsub -v MATLABCMD quant/run.sh 
export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 0; dropout = [0.9\, 0.9]; tot = 2; collo = 1; dataflag='subj'; name='/scr/sbowman/subjt-'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo);" ; qsub -v MATLABCMD quant/run.sh


export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 0; dropout = [0.9\, 0.9]; tot = 2; collo = 1; dataflag='subj-transfer'; name='/scr/sbowman/subjt2'; TrainModel('snlirc-snlirc2-only-l1e-07-dim50-ed200-td3-pen100-do0.9-0.9-co1-comp2-dp1/ckpt-best-tr150517185056@353375.mat'\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1);" ; qsub -v MATLABCMD quant/run.sh 
export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 0; dropout = [0.9\, 0.9]; tot = 2; collo = 1; dataflag='subj-transfer'; name='/scr/sbowman/subjt2'; TrainModel('snlirc-snlirc2-only-l1e-07-dim50-ed200-td3-pen100-do0.9-0.9-co1-comp2-dp1/ckpt-best-tr150517185056@353375.mat'\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0);" ; qsub -v MATLABCMD quant/run.sh 
export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 0; dropout = [0.9\, 0.9]; tot = 2; collo = 1; dataflag='subj'; name='/scr/sbowman/subjt2'; TrainModel(''\, 1\, @SUBJ\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 0);" ; qsub -v MATLABCMD quant/run.sh


cd quant; 
lambda = 0.000001; dim = 20; ed = 200; td = 2; penult = 75; dropout = [0.5, 0.5]; tot = 2; collo = 1; dataflag='sst-expanded'; 
name='/scr/sbowman/subj-init'; 
TrainModel('', 1, @SUBJ, name, dataflag, ed, dim, td, penult, lambda, tot, dropout(1), dropout(2), collo, 0, 0, 0, 0.1);
