export MATLABCMD="cd quant; lambda = 0.00001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0.02; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag=''; name='snli'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.00001; dim = 10; ed = 200; td = 1; penult = 75; lr = 0.02; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag=''; name='snli'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8

export MATLABCMD="cd quant; lambda = 0.00001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0.02; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag='sick-only'; name='snli'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8


echo "cd quant; lambda = 0.00001; dim = 10; ed = 200; td = 1; penult = 75; lr = 0.02; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; tscale = 1; wscale = 0.01; mbs = 32; dataflag=''; name='snliT'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 0\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, tscale\, wscale\, 1\, 1);"z

export MATLABCMD="cd quant; lambda = 0.00001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0.02; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; mbs = 32; dataflag=''; name='snli2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.00001; dim = 10; ed = 200; td = 1; penult = 75; lr = 0.02; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; mbs = 32; dataflag=''; name='snli2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 1\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.00001; dim = 30; ed = 200; td = 1; penult = 75; lr = 0.02; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; mbs = 32; dataflag=''; name='snli2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 2\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.00001; dim = 10; ed = 200; td = 1; penult = 75; lr = 0.02; dropout = [0.75\, 0.9]; rtemult = 0; nlimult = 0; mult = 8; wordsource = 1; mbs = 32; dataflag=''; name='snli2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, 2\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, mult\, rtemult\, nlimult\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8

export MATLABCMD="cd quant; lambda = 0.0005; dim = 75; ed = 200; td = 3; penult = 150; lr = 0.02; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; mbs = 64; dataflag='snli-temp-sick'; name='snlit'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 45; ed = 200; td = 3; penult = 75; lr = 0.02; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; mbs = 64; dataflag='snli-temp-sick'; name='snlit'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, 0\, mbs\, lr\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 45; ed = 200; td = 3; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snlib'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.01; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 45; ed = 200; td = 2; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 45; ed = 200; td = 2; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12


export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 0.1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 10);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 0.1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12z
export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli-temp-sick'; name='/scr/sbowman/snli-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 10);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.00001; dim = 75; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 150; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 6);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00000001; dim = 75; ed = 200; td = 1; penult = 150; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 8);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.0000001; dim = 75; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 10);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.00001; dim = 75; ed = 200; td = 2; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 2; penult = 150; dropout = [0.5\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 6);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.00000001; dim = 75; ed = 200; td = 1; penult = 150; dropout = [0.75\, 0.6]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8

export MATLABCMD="cd quant; lambda = 0.00000001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00000001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 150; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0.11\, 6);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 150; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0.33\, 6);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8

export MATLABCMD="cd quant; lambda = 0.0001; dim = 75; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 150; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 20);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00000001; dim = 75; ed = 200; td = 3; penult = 150; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 25; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 8);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.0000001; dim = 75; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 20);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.00001; dim = 75; ed = 200; td = 2; penult = 75; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.0001; dim = 45; ed = 200; td = 2; penult = 150; dropout = [0.5\, 0.9]; tot = 1; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 6);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8
export MATLABCMD="cd quant; lambda = 0.000000001; dim = 75; ed = 200; td = 1; penult = 150; dropout = [0.75\, 0.6]; tot = 1; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -l nodes=1:ppn=8

export MATLABCMD="cd quant; lambda = 0.000001; dim = 20; ed = 200; td = 1; penult = 35; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0; dim = 20; ed = 200; td = 1; penult = 35; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 20; ed = 200; td = 1; penult = 35; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0; dim = 20; ed = 200; td = 1; penult = 35; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.000001; dim = 20; ed = 200; td = 3; penult = 35; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 20; ed = 200; td = 3; penult = 35; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/snli095-f'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 75; ed = 200; td = 3; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-s'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 1; penult = 150; dropout = [0.6\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-s'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 20);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00000001; dim = 45; ed = 200; td = 1; penult = 150; dropout = [0.75\, 0.7]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-s'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 75; ed = 200; td = 1; penult = 75; dropout = [0.6\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-s'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 75; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-s'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 20);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00000001; dim = 75; ed = 200; td = 3; penult = 75; dropout = [0.75\, 0.7]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-s'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0000001; dim = 20; ed = 200; td = 3; penult = 35; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/dgp'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 20; ed = 200; td = 3; penult = 35; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/dgp'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 20; ed = 200; td = 3; penult = 35; dropout = [0.75\, 0.9]; tot = 1; wordsource = 1; dataflag='dg-pre'; name='/scr/sbowman/dgp'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 75; ed = 200; td = 3; penult = 75; dropout = [0.7\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 45; ed = 200; td = 2; penult = 150; dropout = [0.5\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 20);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00000001; dim = 45; ed = 200; td = 2; penult = 150; dropout = [0.7\, 0.7]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 12);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 75; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-sick'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0001; dim = 25; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.75]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 128);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 25; ed = 200; td = 3; penult = 75; dropout = [0.5\, 0.5]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 128);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00000001; dim = 25; ed = 200; td = 2; penult = 125; dropout = [0.75\, 0.75]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 128);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 60; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 128);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 60; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 32);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 25; ed = 200; td = 3; penult = 75; dropout = [0.5\, 0.5]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 32);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.001; dim = 75; ed = 200; td = 3; penult = 75; dropout = [0.7\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 32);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 45; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.65]; tot = 2; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 32);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 75; ed = 200; td = 2; penult = 90; dropout = [0.5\, 0.5]; tot = 2; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 32);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 45; ed = 200; td = 1; penult = 90; dropout = [0.5\, 0.9]; tot = 2; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s4'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 128);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

% Next
export MATLABCMD="cd quant; lambda = 0; dim = 45; ed = 200; td = 3; penult = 75; dropout = [0.9\, 0.5]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-2\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 65; ed = 200; td = 3; penult = 75; dropout = [0.5\, 0.5]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 0.1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0; dim = 45; ed = 200; td = 3; penult = 75; dropout = [0.5\, 0.9]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-1\, 0.1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 25; ed = 200; td = 3; penult = 75; dropout = [0.9\, 0.9]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.001; dim = 25; ed = 200; td = 1; penult = 45; dropout = [0.5\, 0.5]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.0001; dim = 25; ed = 200; td = 1; penult = 45; dropout = [0.5\, 0.5]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 25; ed = 200; td = 1; penult = 45; dropout = [0.5\, 0.5]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 25; ed = 200; td = 1; penult = 45; dropout = [0.5\, 0.5]; tot = 4; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.00001; dim = 75; ed = 200; td = 3; penult = 75; dropout = [0.5\, 0.5]; tot = 2; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 0.11);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 75; ed = 200; td = 3; penult = 75; dropout = [0.5\, 0.5]; tot = 2; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 75; ed = 200; td = 3; penult = 75; dropout = [0.5\, 0.5]; tot = 2; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.00001; dim = 40; ed = 200; td = 3; penult = 25; dropout = [0.5\, 0.5]; tot = 2; wordsource = 1; dataflag='snli095HOL-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 0.11);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 40; ed = 200; td = 3; penult = 25; dropout = [0.5\, 0.5]; tot = 2; wordsource = 1; dataflag='snli095HOL-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.00001; dim = 40; ed = 200; td = 3; penult = 25; dropout = [0.5\, 0.5]; tot = 2; wordsource = 1; dataflag='snli095HOL-only'; name='/scr/sbowman/snli095-s5'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l nodes=1:ppn=12

export MATLABCMD="cd quant; lambda = 0.0000001; dim = 200; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = -1; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s7'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.000001; dim = 200; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = -1; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s7'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 200; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = -1; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s7'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.000001; dim = 200; ed = 200; td = 1; penult = 75; dropout = [1\, 1]; tot = -1; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s8'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 200; ed = 200; td = 1; penult = 75; dropout = [1\, 1]; tot = -1; wordsource = 1; dataflag='snli095-only'; name='/scr/sbowman/snli095-s8'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh


export MATLABCMD="cd quant; lambda = 0.00001; dim = 40; ed = 200; td = 3; penult = 25; dropout = [0.5\, 0.5]; tot = 2; wordsource = 1; dataflag='snli096-only'; name='/scr/sbowman/snli096'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0.11);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
export MATLABCMD="cd quant; lambda = 0.00001; dim = 40; ed = 200; td = 3; penult = 25; dropout = [0.5\, 0.5]; tot = 2; wordsource = 1; dataflag='snli096-only'; name='/scr/sbowman/snli096'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0.33);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
export MATLABCMD="cd quant; lambda = 0.00001; dim = 40; ed = 200; td = 3; penult = 25; dropout = [0.5\, 0.5]; tot = 2; wordsource = 1; dataflag='snli096-only'; name='/scr/sbowman/snli096'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb


export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [0.9\, 0.9]; tot = 2; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
export MATLABCMD="cd quant; lambda = 0.0000001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [0.9\, 0.9]; tot = 2; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb

export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [0.9\, 0.9]; tot = 1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
export MATLABCMD="cd quant; lambda = 0.0000001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [0.9\, 0.9]; tot = 1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb

export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [0.9\, 0.9]; tot = 7; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
export MATLABCMD="cd quant; lambda = 0.0000001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [0.9\, 0.9]; tot = 7; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb


	export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	% 0001 -> 753@21
	% 00001 -> 753@23
	% Chose 00003

	export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	% 001 -> 0.67205@3, others much worse 
	export MATLABCMD="cd quant; lambda = 0.003; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb


	export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	% 1e-5 717 @8
	% 1e-6 718 @8
	% Chose 1e-6...

	export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 0; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 0; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 0; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	% 001 - 689@8
	% 0001 - 709@10
	% 1e-5 - 701@8
	export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 0; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 0; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	% Choose 00003

	export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = -1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = -1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = -1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	% 1e-5 - 712@6
	% 0001 - 721@6
	export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = -1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = -1; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	% Choose 0.0001

	export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 3; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.0001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 3; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 3; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	% 0001 671@3
	% 001 654@3
	export MATLABCMD="cd quant; lambda = 0.001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 3; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	export MATLABCMD="cd quant; lambda = 0.0003; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 3; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=31gb
	% Choose 0001

	export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh -q jag -l mem=12gb
	export MATLABCMD="cd quant; lambda = 0.00001; dim = 200; ed = 200; td = 3; penult = 400; dropout = [1\, 1]; tot = 2; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0);" ; qsub -v MATLABCMD quant/run.sh -q jag -l mem=12gb
	export MATLABCMD="cd quant; lambda = 0.00001; dim = 50; ed = 200; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 1; dataflag='snlirc2-only'; name='/scr/sbowman/snlirc2'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0);" ; qsub -v MATLABCMD quant/run.sh -q jag -l mem=12gb

--
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 2);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 3);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 4);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb


% GC
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0.5\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 50\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 4);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb

% Next round
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 50\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 4);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb

export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 2);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 3);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 4);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb

% Next round
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0.5\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 50\, 2);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 3);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 4);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -q john -l mem=6gb

export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 1);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 2);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 3);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 4);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3b'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb

% Next round
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0.5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 10\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 50\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb

export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [0.5\, 0.5]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [0.75\, 0.75]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 100; dropout = [0.5\, 0.5]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 100; dropout = [0.75\, 0.75]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb -q john

export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 50\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb -q john
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb -q john
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [0.5\, 0.5]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb -q john
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [0.75\, 0.75]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb -q john

% Next round
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0.1\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0.5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 2; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb

export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 0.1\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 1\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 300; td = 3; penult = 100; dropout = [1\, 1]; tot = 7; wordsource = 3; dataflag='snlirc3-only-short'; name='/scr/sbowman/snlirc3c'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 10\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb

% Main training runs


export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.75\, 0.75]; tot = -1; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb -l nodes=1:ppn=6 -q john
export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9\, 0.9]; tot = -1; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb -l nodes=1:ppn=6 -q john

export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 2; penult = 200; dropout = [0.9\, 0.9]; tot = 0; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john

export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 2; penult = 200; dropout = [0.9\, 0.9]; tot = 0; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9\, 0.9]; tot = 0; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 200; dropout = [0.9\, 0.9]; tot = 1; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 25; ed = 300; td = 3; penult = 200; dropout = [0.9\, 0.9]; tot = 1; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john


export MATLABCMD="cd quant; lambda = 0.00003; dim = 50; ed = 300; td = 3; penult = 200; dropout = [0.75\, 0.75]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.75\, 0.75]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 200; ed = 300; td = 3; penult = 200; dropout = [0.75\, 0.75]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.7\, 0.5]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.95\, 0.95]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john

export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9\, 0.9]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john

export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.95\, 0.95]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.95\, 0.95]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0.1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.95\, 0.95]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0.01\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.95\, 0.95]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0.001\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.95\, 0.95]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 0.00015\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john

export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9\, 0.9]; tot = 3; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john

export MATLABCMD="cd quant; lambda = 0.000001; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9\, 0.9]; tot = 7; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john

echo "cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9, 0.9]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3dJ'; TrainModel('', 1, @SNLI, name, dataflag, ed, dim, td, penult, lambda, tot, dropout(1), dropout(2), wordsource, 1, 5, 5);"  | /afs/cs/software/bin/matlab_r2014b -nodisplay
echo "cd quant; lambda = 0.00003; dim = 25; ed = 300; td = 3; penult = 200; dropout = [0.9, 0.9]; tot = 1; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3dJ'; TrainModel('', 1, @SNLI, name, dataflag, ed, dim, td, penult, lambda, tot, dropout(1), dropout(2), wordsource, 1, 5, 5);"   | /afs/cs/software/bin/matlab_r2014b -nodisplay
echo "cd quant; lambda = 0.000001; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9, 0.9]; tot = 7; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3dJ'; TrainModel('', 1, @SNLI, name, dataflag, ed, dim, td, penult, lambda, tot, dropout(1), dropout(2), wordsource, 1, 5, 5);"  | /afs/cs/software/bin/matlab_r2014b -nodisplay
echo "cd quant; lambda = 0.0000003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9, 0.9]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3dJ'; TrainModel('', 1, @SNLI, name, dataflag, ed, dim, td, penult, lambda, tot, dropout(1), dropout(2), wordsource, 1, 5, 5);"   | /afs/cs/software/bin/matlab_r2014b -nodisplay

export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.95\, 0.95]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d-examplelogging'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john


cd quant; 
lambda = 0.000001; dim = 45; ed = 50; td = 2; penult = 75; dropout = [0.5, 0.5]; tot = 1; wordsource = 2; dataflag='snli095short-only'; name='/scr/sbowman/snli095-prof-b'; 
TrainModel('', 1, @SNLI, name, dataflag, ed, dim, td, penult, lambda, tot, dropout(1), dropout(2), wordsource, 1, 5, 5)

-

export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9\, 0.9]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.95\, 0.95]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d-late'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [1.0\, 1.0]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 150; ed = 300; td = 3; penult = 200; dropout = [0.95\, 0.95]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john

export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.8\, 0.8]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.75\, 0.75]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 150; ed = 300; td = 3; penult = 200; dropout = [0.75\, 0.75]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john

export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.95\, 0.95]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d-late'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9\, 0.9]; tot = 2; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d-late'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=3gb  -l nodes=1:ppn=4 -q john
export MATLABCMD="cd quant; lambda = 0.0001; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9\, 0.9]; tot = 3; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d-late'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john
export MATLABCMD="cd quant; lambda = 0.00003; dim = 100; ed = 300; td = 3; penult = 200; dropout = [0.9\, 0.9]; tot = 0; wordsource = 3; dataflag='snlirc3-only'; name='/scr/sbowman/snlirc3d-late'; TrainModel(''\, 1\, @SNLI\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, wordsource\, 1\, 5\, 5);" ; qsub -v MATLABCMD quant/run.sh -l mem=6gb  -l nodes=1:ppn=6 -q john

-

positive lambda better

best: 0.529
