cd quant; 
lambda = 0.000001; dim = 30; ed = 200; td = 2; penult = 75; dropout = [0.5, 0.5]; tot = 4; collo = 1; dataflag='sst'; name='/scr/sbowman/sst-test'; 
TrainModel('', 1, @SST, name, dataflag, ed, dim, td, penult, lambda, tot, dropout(1), dropout(2), collo)

export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = 4; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = 3; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = -1; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh


export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = 4; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; dropout = [0.75\, 0.75]; tot = 4; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; dropout = [1\, 1]; tot = 4; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.01; dim = 30; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = 4; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.0001; dim = 30; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = 4; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh
export MATLABCMD="cd quant; lambda = 0.000001; dim = 30; ed = 200; td = 1; penult = 75; dropout = [0.5\, 0.5]; tot = 4; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh

export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 200; td = 2; penult = 75; dropout = [0.5\, 0.5]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh  -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 30; ed = 200; td = 2; penult = 75; dropout = [0.75\, 0.75]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1\, 1);" ; qsub -v MATLABCMD quant/run.sh  -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 20; ed = 200; td = 3; penult = 75; dropout = [0.5\, 0.75]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh  -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 80; ed = 200; td = 1; penult = 150; dropout = [0.75\, 0.5]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh  -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 50; ed = 200; td = 2; penult = 150; dropout = [0.5\, 0.75]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh  -q john -l nodes=1:ppn=12
export MATLABCMD="cd quant; lambda = 0.000001; dim = 80; ed = 200; td = 2; penult = 75; dropout = [0.75\, 0.75]; tot = 2; collo = 1; dataflag='sst-expanded'; name='/scr/sbowman/sst-expanded-2'; TrainModel(''\, 1\, @SST\, name\, dataflag\, ed\, dim\, td\, penult\, lambda\, tot\, dropout(1)\, dropout(2)\, collo\, 1e-4\, 1);" ; qsub -v MATLABCMD quant/run.sh  -q john -l nodes=1:ppn=12
